PLEASE THINK A NOTHER SOLUTION FOR THAT AND FIX THAT ERROR, THE ERROR APPEAR AT QUESTION 13, COULD BE MATCHHING QUESTION CAUSE TAHT:
Runtime Error

Error: A <Select.Item /> must have a value prop that is not an empty string. This is because the Select value can be set to an empty string to clear the selection and show the placeholder.

src/components/ui/select.tsx (118:3) @ _c8

  116 |   React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>
  117 | >(({ className, children, ...props }, ref) => (
> 118 |   <SelectPrimitive.Item
      |   ^
  119 |     ref={ref}
  120 |     className={cn(
  121 |       "relative flex w-full cursor-default select-none ite